//2nd step -> create constant (3rd step back in actions.js)
export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

//STANDARD FOR ASYNC FUNCTIONS
export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PEDING';
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILED = 'REQUEST_ROBOTS_FAILED';
